# Generated by Django 5.1 on 2025-04-19 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, choices=[('I', 'Tarapacá'), ('II', 'Antofagasta'), ('III', 'Atacama'), ('IV', 'Coquimbo'), ('V', 'Valparaíso'), ('RM', 'Región Metropolitana'), ('VI', 'Libertador General Bernardo O’Higgins'), ('VII', 'Maule'), ('VIII', 'Biobío'), ('IX', 'La Araucanía'), ('X', 'Los Lagos'), ('XI', 'Aysén del General Carlos Ibáñez del Campo'), ('XII', 'Magallanes y de la Antártica Chilena'), ('XIV', 'Los Ríos'), ('XV', 'Arica y Parinacota'), ('XVI', 'Ñuble')], max_length=30, null=True)),
                ('direction', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Studio', 'Studio')], max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Available'), ('O', 'Occupied'), ('M', 'Maintenance')], max_length=20, null=True)),
                ('qty_bathrooms', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('qty_rooms', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('area', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='users.profileuser')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rental_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Internet', 'Internet'), ('Gas', 'Gas'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=50, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='rental_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Available'), ('O', 'Occupied'), ('M', 'Maintenance')], max_length=1, null=True)),
                ('size', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=10, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rental_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_leave', models.TextField(blank=True, max_length=200, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to='users.profileuser')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='rental_app.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='rental_app.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'room', 'check_in')},
            },
        ),
    ]
